[theme]
primaryColor = "#1E90FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
headless = false
port = 8501
